name: "ensemble"
platform: "ensemble"

input [
    {
        name: "TEXTS"
        data_type: TYPE_STRING
        dims: [ -1 ]
    }
]

output [
    {
        name: "EMBEDDINGS-ONNX"
        data_type: TYPE_FP32
        dims: [ 96 ]
    },
    {
        name: "EMBEDDINGS-TRT-FP32"
        data_type: TYPE_FP32
        dims: [ 96 ]
    },
    {
        name: "EMBEDDINGS-TRT-FP16"
        data_type: TYPE_FP16
        dims: [ 96 ]
    },
    {
        name: "EMBEDDINGS-TRT-INT8"
        data_type: TYPE_INT8
        dims: [ 96 ]
    },
    {
        name: "EMBEDDINGS-TRT-BEST"
        data_type: TYPE_FP32
        dims: [ 96 ]
    }
]

ensemble_scheduling {
    step [
        {
            model_name: "tokenizer"
            model_version: -1
            input_map {
                key: "TEXTS"
                value: "TEXTS"
            }
            output_map {
                key: "INPUT_IDS"
                value: "INPUT_IDS"
            }
            output_map {
                key: "ATTENTION_MASK"
                value: "ATTENTION_MASK"
            }
        },
        {
            model_name: "embedder-onnx"
            model_version: -1
            input_map {
                key: "INPUT_IDS"
                value: "INPUT_IDS"
            }
            input_map {
                key: "ATTENTION_MASK"
                value: "ATTENTION_MASK"
            }
            output_map {
                key: "EMBEDDINGS"
                value: "EMBEDDINGS-ONNX"
            }
        },
        {
            model_name: "embedder-trt-fp32"
            model_version: -1
            input_map {
                key: "INPUT_IDS"
                value: "INPUT_IDS"
            }
            input_map {
                key: "ATTENTION_MASK"
                value: "ATTENTION_MASK"
            }
            output_map {
                key: "EMBEDDINGS"
                value: "EMBEDDINGS-TRT-FP32"
            }
        },
        {
            model_name: "embedder-trt-fp16"
            model_version: -1
            input_map {
                key: "INPUT_IDS"
                value: "INPUT_IDS"
            }
            input_map {
                key: "ATTENTION_MASK"
                value: "ATTENTION_MASK"
            }
            output_map {
                key: "EMBEDDINGS"
                value: "EMBEDDINGS-TRT-FP16"
            }
        },
        {
            model_name: "embedder-trt-int8"
            model_version: -1
            input_map {
                key: "INPUT_IDS"
                value: "INPUT_IDS"
            }
            input_map {
                key: "ATTENTION_MASK"
                value: "ATTENTION_MASK"
            }
            output_map {
                key: "EMBEDDINGS"
                value: "EMBEDDINGS-TRT-INT8"
            }
        },
        {
            model_name: "embedder-trt-best"
            model_version: -1
            input_map {
                key: "INPUT_IDS"
                value: "INPUT_IDS"
            }
            input_map {
                key: "ATTENTION_MASK"
                value: "ATTENTION_MASK"
            }
            output_map {
                key: "EMBEDDINGS"
                value: "EMBEDDINGS-TRT-BEST"
            }
        }
    ]
}